# Generated by Django 5.0.2 on 2024-02-13 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0002_remove_userprofile_user_remove_userprofile_fields_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=256)),
                ('kode_identitas', models.CharField(max_length=256)),
                ('role', models.CharField(choices=[('LEC', 'Dosen'), ('STU', 'Mahasiswa')], default='STU', max_length=3)),
                ('is_external', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('major', models.CharField(max_length=256)),
                ('about', models.TextField(blank=True)),
                ('profile_image', models.CharField(blank=True, max_length=256)),
                ('line_id', models.CharField(blank=True, max_length=256)),
                ('linkedin_url', models.CharField(blank=True, max_length=256)),
                ('github_url', models.CharField(blank=True, max_length=256)),
                ('is_open', models.BooleanField(default=True)),
                ('fields', models.ManyToManyField(related_name='field_of_interest', to='marketplace.field')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userprofile')),
            ],
        ),
    ]
