# Generated by Django 5.0.2 on 2024-02-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='kode_identitas',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='educational_program',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='faculty',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='study_program',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
