# Generated by Django 5.0.2 on 2024-02-15 14:07

import api.user.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, storage=api.user.storage.ImageStorage(), upload_to='profile_imgs/'),
        ),
    ]
