# Generated by Django 5.0.3 on 2024-03-29 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicinformation',
            name='topic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='marketplace.topic'),
        ),
    ]
