# Generated by Django 5.0.4 on 2024-05-03 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicrequest',
            name='is_open',
        ),
    ]
