# Generated by Django 5.0.4 on 2024-05-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='is_approved',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='applicationapproval',
            name='is_approved',
            field=models.BooleanField(blank=True),
        ),
    ]
