# Generated by Django 5.0.4 on 2024-05-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_remove_topicrequest_is_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicrequest',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
