# Generated by Django 5.0.4 on 2024-05-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_alter_application_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='is_approved',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='applicationapproval',
            name='is_approved',
            field=models.BooleanField(null=True),
        ),
    ]
