# Generated by Django 5.0.1 on 2024-02-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_application_applicationapproval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationapproval',
            name='deleted_on',
            field=models.DateTimeField(blank=True),
        ),
    ]
