# Generated by Django 5.0.4 on 2024-05-06 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_topicrequest_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicrequest',
            name='is_approved',
            field=models.BooleanField(null=True),
        ),
    ]
