# Generated by Django 5.0.4 on 2024-05-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_topicrequest_is_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='user',
            new_name='creator',
        ),
        migrations.AddField(
            model_name='applicationapproval',
            name='approval_status',
            field=models.IntegerField(choices=[(-1, 'Declined'), (0, 'Waiting'), (1, 'Accepted'), (2, 'Moved')], default=0),
        ),
        migrations.AddField(
            model_name='topicrequestapproval',
            name='approval_status',
            field=models.IntegerField(choices=[(-1, 'Declined'), (0, 'Waiting'), (1, 'Accepted'), (2, 'Moved')], default=0),
        ),
    ]
