# Generated by Django 5.0.1 on 2024-02-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_alter_applicationapproval_deleted_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationapproval',
            name='deleted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
