# Generated by Django 5.0.1 on 2024-02-07 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_alter_applicationapproval_deleted_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinformation',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='marketplace.course'),
        ),
    ]
