# Generated by Django 5.0.4 on 2024-05-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_rename_user_application_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicrequestapproval',
            name='approval_status',
            field=models.IntegerField(choices=[(-1, 'Declined'), (0, 'Waiting'), (1, 'Accepted'), (2, 'All Accepted'), (3, 'Moved')], default=0),
        ),
    ]
