# Generated by Django 5.0.1 on 2024-02-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_alter_courseinformation_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('OO', 'One to One'), ('OM', 'One to Many')], max_length=2),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_allowed_new_topic',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='topic',
            name='num_of_people',
            field=models.IntegerField(),
        ),
    ]
