# Generated by Django 5.0.4 on 2024-05-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_alter_application_applicants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationapproval',
            name='approval_status',
            field=models.IntegerField(choices=[(-1, 'Declined'), (0, 'Waiting'), (1, 'Accepted'), (2, 'All Accepted'), (3, 'Moved')], default=0),
        ),
    ]
