# Generated by Django 5.0.1 on 2024-02-06 15:45

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('course_type', models.CharField(choices=[('OO', 'One to One'), ('OM', 'One to Many')], default='OO', max_length=2)),
                ('is_allowed_new_topic', models.BooleanField(default=True)),
                ('topic_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'courses',
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('code', models.CharField(max_length=2)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
                ('kode_identitas', models.CharField(max_length=256)),
                ('role', models.CharField(choices=[('LEC', 'Dosen'), ('STU', 'Mahasiswa')], default='STU', max_length=3)),
                ('is_external', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Prerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SKS', 'Jumlah SKS'), ('SMT', 'Semester'), ('CRS', 'Mata Kuliah')], default='SKS', max_length=3)),
                ('minimum', models.IntegerField(default=0)),
                ('maximum', models.IntegerField(blank=True, default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.course')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('is_open', models.BooleanField(default=True)),
                ('num_of_people', models.IntegerField(default=1)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.course')),
                ('fields', models.ManyToManyField(to='marketplace.field')),
                ('supervisors', models.ManyToManyField(to='marketplace.user')),
            ],
        ),
        migrations.CreateModel(
            name='TopicInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html', ckeditor.fields.RichTextField()),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.topic')),
            ],
        ),
    ]
