# Generated by Django 5.0.3 on 2024-04-02 06:10

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('kd_mk', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nm_mk', models.CharField(max_length=256)),
                ('sks', models.IntegerField()),
                ('course_type', models.CharField(choices=[('OO', 'One to One'), ('OM', 'One to Many')], max_length=2)),
                ('is_allowed_new_topic', models.BooleanField()),
                ('topic_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'courses',
            },
        ),
        migrations.CreateModel(
            name='CourseInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html', ckeditor.fields.RichTextField()),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='academic.course')),
            ],
        ),
        migrations.CreateModel(
            name='Prerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SKS', 'Jumlah SKS'), ('SMT', 'Semester'), ('CRS', 'Mata Kuliah')], default='SKS', max_length=3)),
                ('minimum', models.IntegerField(default=0)),
                ('maximum', models.IntegerField(blank=True, default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.course')),
            ],
        ),
    ]
