# Generated by Django 5.0.3 on 2024-03-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='kd_mk',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
