# Generated by Django 5.0.4 on 2024-05-02 14:42

import api.activity.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='marketplace.application')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.course')),
                ('supervisee', models.ManyToManyField(related_name='supervisee', to=settings.AUTH_USER_MODEL)),
                ('supervisors', models.ManyToManyField(related_name='supervisors', to=settings.AUTH_USER_MODEL)),
                ('topic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='marketplace.topic')),
            ],
        ),
        migrations.CreateModel(
            name='FileSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=256)),
                ('body', models.TextField()),
                ('file', models.FileField(storage=api.activity.storage.FileStorage(), upload_to='assignments/')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.activity')),
                ('assignment_component', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='academic.assignmentcomponent')),
            ],
        ),
        migrations.CreateModel(
            name='LogSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=256)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.activity')),
                ('assignment_component', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='academic.assignmentcomponent')),
            ],
        ),
        migrations.CreateModel(
            name='StepCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.activity')),
                ('activity_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.activitystep')),
            ],
        ),
    ]
