# Generated by Django 5.0.4 on 2024-05-02 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='supervisor',
            new_name='supervisors',
        ),
    ]
