# Generated by Django 5.0.4 on 2024-05-03 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
        ('marketplace', '0002_remove_topicrequest_is_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='topic_request',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='marketplace.topicrequest'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='application',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='marketplace.application'),
        ),
    ]
