# Generated by Django 5.0.4 on 2024-05-04 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_activity_topic_request_alter_activity_application'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='supervisee',
            new_name='supervisees',
        ),
    ]
