# Generated by Django 5.0.4 on 2024-05-02 10:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_rename_supervisor_activity_supervisors'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='supervisors',
            field=models.ManyToManyField(related_name='supervisors', to=settings.AUTH_USER_MODEL),
        ),
    ]
