# Generated by Django 5.0.4 on 2024-05-04 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_rename_supervisee_activity_supervisees'),
        ('marketplace', '0003_topicrequest_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='marketplace.application'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='topic_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='marketplace.topicrequest'),
        ),
    ]
