# Generated by Django 5.0.4 on 2024-05-04 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_alter_activity_application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesubmission',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filesubmissions', to='activity.activity'),
        ),
        migrations.AlterField(
            model_name='filesubmission',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filesubmission',
            name='subject',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='logsubmission',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logsubmissions', to='activity.activity'),
        ),
        migrations.AlterField(
            model_name='stepcompletion',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stepcompletions', to='activity.activity'),
        ),
    ]
