# Generated by Django 5.0.4 on 2024-05-04 08:44

import api.activity.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_alter_filesubmission_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesubmission',
            name='file',
            field=models.FileField(max_length=1000, storage=api.activity.storage.FileStorage(), upload_to='assignments/'),
        ),
    ]
