# Generated by Django 5.0.4 on 2024-05-04 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        ('activity', '0006_alter_filesubmission_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesubmission',
            name='assignment_component',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='academic.assignmentcomponent'),
        ),
    ]
