# Generated by Django 5.0.4 on 2024-05-07 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        ('activity', '0007_alter_filesubmission_assignment_component'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesubmission',
            name='assignment_component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='academic.assignmentcomponent'),
        ),
        migrations.AlterUniqueTogether(
            name='filesubmission',
            unique_together={('assignment_component', 'activity')},
        ),
    ]
