# Generated by Django 5.0.4 on 2024-05-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0008_alter_filesubmission_assignment_component_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_completed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
