# Generated by Django 5.0.4 on 2024-05-10 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        ('activity', '0009_activity_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesubmission',
            name='assignment_component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='filesubmissionassignments', to='academic.assignmentcomponent'),
        ),
        migrations.AlterField(
            model_name='logsubmission',
            name='assignment_component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='logsubmissionassignments', to='academic.assignmentcomponent'),
        ),
    ]
